apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "templating-deep-dive.fullname" . }} # This uses the name specified during helm install/upgrade, and then the name of the chart
  labels:
    {{- include "templating-deep-dive.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "templating-deep-dive.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "templating-deep-dive.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPorts.http }}
