## @param customName allows to set a custome resource name for the deployment
##        Defaults to {{ .Release.Name }}-{{ .Chart.Name }} if not set
customName: ''

# Replica count
# Image, both name and tag
# Service type and port

## @param replicaCount The number of Nginx replicas to deploy
replicaCount: 3

# Used to show that you can use if statements depending on the environment
## @param environment The deployment environment
# environment: production

## Setting for Nginx image
##
## @param image.name The Nginx image name to use
## @param image.tag The Nginx image tag to use
image: 
  name: nginx
  tag: "1.29.3"

## Nginx container ports
##
## @param containerPorts.http
containerPorts:
  http: 80

## Settings for Nginx service
## services is a map with the following schema
##
## @param services[*].type The type of Kubernetes service to create
## @param services[*].port The port for the Nginx service
services:
  svc1:
    type: ClusterIP
    port: 80
  svc2: 
    type: NodePort
    port: 30007
